config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:destroy]

  resources :lists, except: [:edit] do
    resources :items, only: [:create]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items

  def sorted_items
    self.items.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:destroy]

  # POST /items
  def create
    @item = Item.new(item_params)
    @item.list_id = params[:list_id]

    if @item.save
      redirect_to @item.list, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to @item.list, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :url, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show
    @item = Item.new
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      render json: @list
    else
      render status: :not_acceptable
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.slim
= form_for [@list, @item] do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .actions = f.submit 'Save'

app/views/layouts/application.html.slim
doctype html
html
  head
    title listem
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    == yield

app/views/lists/_form.html.slim
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      h2 = "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      ul
        - @list.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit 'Save'

app/views/lists/index.html.slim
h1 Listing lists

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @lists.each do |list|
      tr
        td = list.title
        td = link_to 'Show', list
        td = link_to 'Destroy', list, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New List', new_list_path

app/views/lists/new.html.slim
h1 New list

== render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.slim
p#notice = notice

h1 contenteditable="true"
  = @list.title
ul
  li
    == render 'items/form'
  - @list.sorted_items.each do |item|
    li
      == link_to item.title, item.url
      '
      == link_to 'x', item_url(item), method: :delete

= link_to 'Back', lists_path